### PR TITLE
Update: make compatible with @quasar/app-vite

### PR DESCRIPTION
**Pull request by NicolasReibnitz**
Hi Luke,

Like with [vueauth/quasar-ui-auth](https://github.com/vueauth/quasar-ui-auth), this PR makes the extension compatible with @quasar/app-vite. The necessary changes were minimal.

There is a bigger issue here though: the npm package [@vuemodel/supabase](https://www.npmjs.com/package/@vuemodel/supabase) can't be digested by Vite:

> ✘ [ERROR] [plugin vite:dep-pre-bundle] Failed to resolve entry for package "@vuemodel/supabase". The package may have incorrect main/module/exports specified in its package.json: Failed to resolve entry for package "@vuemodel/supabase". The package may have incorrect main/module/exports specified in its package.json.

This error turned out to be a red herring! The problem is the readme entry in the package.json file on line 53. Something in there might not be properly escaped or something. VSCode doesn't complain, though.
My quick look plugin in macOS finder didn't like it either:
json-error
Removing the whole line fixes the problem, and everything works like a charm.

But as the package.json file in the repository doesn't have this entry, I can't make a pull request for this.

As usual: thanks for your excellent work!
Nicolas

### CODE REVIEW

**Comment by NicolasReibnitz** [comment]
The second commit fixes the problem with the configuration file being created in `/src/config/supabase.js` instead of `/config/supabase.js`. But the check for the existence of the file is looking in `/config/`.

This is also how vueauth/quasar-ui-auth sets it up. So I removed the `src` folder in the template directory and updated the readme accordingly. Now it is consistent throughout all the extensions and libraries.

**Comment by NicolasReibnitz** [comment]
Okay, I was wrong about the package.json being the problem here. I guess I got lost in the linked packages in my node_modules folder. 😄 My first attempt to fix the Vite error by rebuilding the package as ESM was really what fixed it.
But it can be fixed by importing `@vuemodel/supabase/src/main` instead of `@vuemodel/supabase` as well. But you'd have to import it that way in your Quasar app as well. So offering a pure ESM module might be the better attempt here.

But there are a couple of other changes one would have to make in order to get all of this working. I'll outline them in a minute. Stay tuned. 🤓

**Comment by NicolasReibnitz** [comment]
Here are all the adjustments I had to make to get your [YouTube example](https://www.youtube.com/watch?v=bJTz7h3o44I) up and running with Vite. I think most if not all of this can be fixed on the package level.

### .eslintrc.js

If you insist on using the absurdly modern syntax of vuex-orm, you would have to set `parserOptions.ecmaVersion` to `latest`. `2021` doesn't cut it.

Another option is to rewrite (for example)

```js
static entity = 'users';
```

to

```js
static get entity() {
  return 'users';
}
```

Both work fine.

### src/store/QuasarVuexOrmPlugin.js

`require.context(...)` doesn't work with Vite out of the box. But there is a Vite plugin that makes the problem go away: [@originjs/vite-plugin-require-context](https://www.npmjs.com/package/@originjs/vite-plugin-require-context).

You would add it as usual in `quasar.config.js`.

Require it somewhere at the top (note the .default at the end of the line)...

```js
const ViteRequireContext = require('@originjs/vite-plugin-require-context').default;
```

and execute it in the `vitePlugins` array:

```js
vitePlugins: [[ViteRequireContext()]];
```

You also have to change the path slightly by adding a slash at the beginning. `/src/models` vs. `src/models`:

```js
const modelFileContext = require.context('/src/models', false, /\.js$/);
```

An alternative might be to use [Glob Imports](https://vitejs.dev/guide/features.html#glob-import). But I don't know how well that would work with Webpack.

### @vuemodel/supabase

As long as the package isn't compiled as an ES module, you have to import `@vuemodel/supabase`, bypassing the bundle in the dist folder entirely.

Like so:

```js
import { useModelCollection } from '@vuemodel/supabase/src/main';
```

Which I don't understand because Vite should be able to deal with CommonJS modules just fine, right? I'd really like to know why that is because it happens a lot.

Okay, hope this helps!

Cheers,
Nicolas

**Comment by NicolasReibnitz** [comment]
I made an example repository if something isn't clear or as a reference:

[vuemodel-supabase-vite-example](https://github.com/NicolasReibnitz/vuemodel-supabase-vite-example)

This setup works for me. The `quasar-app-extension-supabase` module should get patched automatically after running `npm install`.

**Comment by ldiebold** [comment]
Thankyou! Merged :)

**Pull request merged**
